# Generated by Django 3.2.7 on 2021-10-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.EmailField(max_length=254)),
                ('password_text', models.CharField(max_length=32)),
            ],
        ),
    ]
