# Generated by Django 3.2.7 on 2021-10-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakeError', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='email_text',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='password_text',
            new_name='password',
        ),
    ]
